### ISSUE TITLE
bug: pip install failed

### ISSUE THREAD

**Issue by bonito-skipjack** [tensorchord/envd#1238]
## Description
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye
Python 3.11.0
pip 22.3.1
Docker version 20.10.21, build baeda1f
Linux debian-gnu-linux-11 5.10.0-19-arm64 #1 SMP Debian 5.10.149-2 (2022-10-21) aarch64 GNU/Linux

pip install --pre --upgrade envd
Collecting envd
  Using cached envd-0.2.5rc1.tar.gz (264 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      bash: line 1: go: command not found
      fatal: not a git repository (or any of the parent directories): .git
      fatal: not a git repository (or any of the parent directories): .git
      fatal: not a git repository (or any of the parent directories): .git
      bash: line 2: go: command not found
      make: *** [Makefile:104: build-release] Error 127
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-dnv1n6xv/envd_97b2fc63c22941748ccefd3a4e90326b/setup.py", line 98, in <module>
          version=get_version(),
                  ^^^^^^^^^^^^^
        File "/tmp/pip-install-dnv1n6xv/envd_97b2fc63c22941748ccefd3a4e90326b/setup.py", line 73, in get_version
          build_envd_if_not_found()
        File "/tmp/pip-install-dnv1n6xv/envd_97b2fc63c22941748ccefd3a4e90326b/setup.py", line 42, in build_envd_if_not_found
          assert errno == 0, "Failed to build envd"
      AssertionError: Failed to build envd
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

## Reproduction
pip install --pre --upgrade envd

**Comment by gaocegege** [comment]
Thanks for the issue!

Are you running on X86_64 or ARM64?

**Comment by gaocegege** [comment]
Oh I see. ARM.

**Comment by kemingy** [comment]
Thanks for your feedback. So far, we don’t have Linux ARM release. You can
try to build from the source code by installing golang and run the pip
install again.

**Comment by gaocegege** [comment]
```yaml
    - name: Configure linux build environment
      if: runner.os == 'Linux'
      run: |
        mkdir -p bin
        mv dist/envd_linux_amd64_v1/envd bin/envd
        chmod +x bin/envd
    - name: Configure macOS build environment
      if: runner.os == 'macOS'
      run: |
        mkdir -p bin
        mv dist/envd_darwin_all/envd bin/envd
        chmod +x bin/envd
    - name: Build wheels
      uses: pypa/cibuildwheel@v2.11.2
      env:
        CIBW_ARCHS_MACOS: arm64, x86_64
        CIBW_ARCHS_LINUX: auto64
```

Here we can have a new branch to copy `dist/envd_linux_arm64/envd` to `bin/envd`. Then upload it.
