### ISSUE TITLE
feat: make e2e test faster

### ISSUE THREAD

**Issue by kemingy** [tensorchord/envd#1248]
## Description

Solution:
* split into different action jobs
* option: check if we can run all the ginkgo Describe parallel with GitHub Actions

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by cutecutecat** [comment]
ref:
https://www.testmo.com/guides/github-actions-parallel-testing
https://github.com/testmoapp/example-github-parallel

**Comment by cutecutecat** [comment]
We would use 
```python
proc = subprocess.run(
        ["ginkgo", "outline", "--format", "json", f"{file}"], capture_output=True
    )
```
to extract all description of testcase file at `e2e/*/*.go`, and output to stdin:

```shell
$ python .github/parallel_mat_gen.py 
execute python demo.py
should build successfully
should build successfully
add some blank to build.envd
exec installed command inside container
init python env
should get the environments successfully
fail to delete the current context
should be able to build image with TCP context
should find a new context
should found the default context
should up and destroy successfully
Should build conda with separate channel setting successfully
Should build conda with channel successfully
Should build hybrid successfully
Should build requirements successfully
Should build packages successfully
execute runtime command `numpy`
should be able to build the GPU example
should be able to use envdlib
undefined
can check envd envs details
can list envd envs
```

Then collect them into a `matrix`, and assign each job for one description by `ginkgo --focus ${ desp }`

By this way, we could run one job for one ginkgo `It` testcase.

The `undefined` is by a bad extraction from dynamic string format
https://github.com/tensorchord/envd/blob/8e9cb2e7bcbaef7c86996d7376ca27af8e741ed0/e2e/docs/docs_test.go#L72

I would do a loop unrolling to lei it static.

**Comment by kemingy** [comment]
I don't want to hack GitHub actions for the dynamic matrix. Because their internal API changes frequently without notifying people.

More importantly, we should check the limit before researching the solution: https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration

So actually, we can only run 20 concurrent jobs. There is no need to run all the "Describe" in parallel.

**Comment by cutecutecat** [comment]
> I don't want to hack GitHub actions for the dynamic matrix. Because their internal API changes frequently without notifying people.
> 
> More importantly, we should check the limit before researching the solution: https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration
> 
> So actually, we can only run 20 concurrent jobs. There is no need to run all the "Describe" in parallel.

@kemingy 
Let's make `parallel_mat_gen.py ` into `run_test_job_balance.py` and give it two arguments `ci_index` and `ci_total`.
```yml
ci_index: [0, 1, 2, 3, 4, 5, 6, 7, 8]
ci_total: [8]
```
After it scanned all `Describe`, it will run jobs of index likes `index % ci_total == ci_index`.

As for 20 Describes, `run_test_job_balance.py 3 8` will run index `3`, `11`, `19` Describes.

For default `ci_total`, we could try it for `8`, `9` and `7`, as we have `2 * ci_total` jobs for ubuntu and macos tests, and reserve a few for other jobs.

**Comment by cutecutecat** [comment]
> I think the CI can organize the jobs (even when it's larger than the limit).
> 
> My main concern is the complexity. The current CI is already overwhelming to maintain.

If we don't insert an automatic scanning into CI, then we would make a intrusive revision of tests, to indicate which job it will runs on. 
When we implement new tests, we need to check which job has less test and insert test into it.
If we change the job total number by some reason, we would do a huge rearrangement.

By this way, the complexity don't disappeared, but moved into the source of test.

**Comment by cutecutecat** [comment]
> > By this way, the complexity don't disappeared, but moved into the source of test.
> 
> Make sense. Not sure if there is a stable method to generate the matrix dynamically.


By twice way, we could use a static matrix like this:
ref: https://github.com/tensorchord/envd/issues/1248#issuecomment-1341889333

```
# .github/workflows/build.yml
name: Build

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Building .."

  test:
    needs: build
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ci_index: [0, 1, 2, 3]
        ci_total: [4]

    steps:
      - uses: actions/checkout@v2
      - run: run tests load balance
      - run: python run_test_job_balance.py ${CI_INDEX} ${ CI_INDEX }
        env:
          CI_TOTAL: ${{ matrix.ci_total }}
          CI_INDEX: ${{ matrix.ci_index }}

```
