### ISSUE TITLE
bug(pytorch): Investigate why pytorch pip cache is flaky

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/envd#1359]
## Additional Info

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by kemingy** [comment]
It's due to the cache size.

PyTorch is around 2GB. By default, the limit is:

https://github.com/moby/buildkit/blob/617b78cb69a5d937d4fbe023c269f4d84d80252f/cmd/buildkitd/config/gcpolicy_unix.go#L10-L18

The result for my laptop is 3.25 GB. So it may trigger the GC after installing PyTorch.

This can be configured by https://github.com/moby/buildkit/blob/master/docs/buildkitd.toml.md

**Comment by kemingy** [comment]
Sorry, it's byte not bit, so the size should be 26GB. After `envd pruning`, the cache works.

I don't know if we need to edit the config for the buildkit. It seems reasonable.

**Comment by kemingy** [comment]
I tried to change the cache size to following:

```toml
[worker.oci]
gckeepstorage = 1000

[[worker.oci.gcpolicy]]
    keepBytes = 1024000000
    keepDuration = 172800
    filters = [ "type==source.local", "type==exec.cachemount", "type==source.git.checkout"]

[[worker.oci.gcpolicy]]
    all = true
    keepBytes = 1024000000

[worker.containerd]
gckeepstorage = 1000

[[worker.containerd.gcpolicy]]
    keepBytes = 1024000000
    keepDuration = 172800 # in seconds
    filters = [ "type==source.local", "type==exec.cachemount", "type==source.git.checkout"]

[[worker.containerd.gcpolicy]]
    all = true
    keepBytes = 1024000000
```

Rebuild the Python image cannot re-use the conda cache and following.

This verified that the cache size may affect the layer cache.
