### ISSUE TITLE
bug:  Failed to build envd Image with CUDA 12 and Above

### ISSUE THREAD

**Issue by MondayCha** [tensorchord/envd#1998]
### Are you use the envd server?

- [ ] Yes, I am using the envd server.
- [x] No, I am not using the envd server.

### Describe the bug

I am encountering an issue while attempting to install an envd image on CUDA versions higher than 12. Specifically, my `envd` file specifies the command `install.cuda(version="12.8.1")`, but this results in an error during the build process:

```
[+] ⌚ parse build.envd and download/cache dependencies 3.3s  
FATA[2025-03-20T13:04:46+08:00] exit app=envd error="failed to build the image: failed to compile: failed to compile build.envd: failed to compile the graph: failed to get the base image: failed to get the image config, check if the image(docker.io/nvidia/cuda:12.8.1-cudnn8-devel-ubuntu22.04) exists: failed to get image source from ref: reading manifest 12.8.1-cudnn8-devel-ubuntu22.04 in docker.io/nvidia/cuda: manifest unknown" version=v1.1.0
```

It appears that this issue is related to changes in Nvidia's official tag naming conventions for their Docker images. As of recent updates, tags no longer include a specific number after "cudnn", such as seen in newer examples like [`12.6.3-cudnn-runtime-ubuntu20.04`](https://hub.docker.com/r/nvidia/cuda/tags?name=12.6).

Could you please provide guidance or a workaround to resolve this issue? It seems necessary to adapt the `build.envd` configuration to align with the updated Docker image naming conventions used by Nvidia.

### To Reproduce

```python
# syntax=v1

def build():
    base(dev=True)
    install.conda()
    install.python(version="3.10")
    config.repo(
        url="https://github.com/tensorchord/envd",
        description="envd quick start example",
    )
    envdlib = include("https://github.com/tensorchord/envdlib")
    envdlib.mirror(pip="tuna", conda="tuna")
    install.cuda(version="12.8.1",cudnn="")
    shell("zsh")
    install.apt_packages(name=["sudo"])
    config.jupyter()
```

### The `docker info` output

```yaml
Client: Docker Engine - Community
 Version:    27.4.0
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.19.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.31.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 42
 Server Version: 27.4.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 88bf19b2105c8b17560993bee28a01ddc2f97182
 runc version: v1.2.2-0-g7cb3632
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.8.0-52-generic
 Operating System: Ubuntu 22.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 15.34GiB
 Name: act-1
 ID: f790e8a7-663d-4079-9409-5bcc3adf7d9d
 Docker Root Dir: /mnt/data/docker
 Debug Mode: false
 HTTP Proxy: http://192.168.5.58:1080/
 HTTPS Proxy: http://192.168.5.58:1080/
 No Proxy: localhost,127.0.0.1,.example.com,.cn
 Username: mondaycha
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

### The `envd version` output

```toml
envd: v1.1.0
  BuildDate: 2025-03-10T01:53:17Z
  GitCommit: 1c327cb7ecdec6386b315a34fe01072905221392
  GitTreeState: clean
  GitTag: v1.1.0
  GoVersion: go1.24.1
  Compiler: gc
  Platform: linux/amd64
```
