### ISSUE TITLE
bug: conda env file channel is not used by envd

### ISSUE THREAD

**Issue by kemingy** [tensorchord/envd#830]
## Description

```py
install.conda_packages(env_file="environment.yaml")
```

```yaml
name: test
channels:
  - pytorch
  - defaults
dependencies:
  - pytorch
````

The channel info in the environment.yaml file will be ignored.

## Additional Info

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
